defaults:
  - _self_
  - datasets:
      - aligned_celeba
  - training: full_training_FG
  - wandb: defaults_FG
  - augmentation: 
    - fg_aug
  - model: stylegan3
  - evaluation: FG_evaluation
  - debug_datasets:
    - debug_cropped_celeba
  - mode: default # Set to "debug" when debugging
  - optional local: local.yaml
  - ranking: default_FG.yaml

seed: 1
project_name: face_generation

check_dataset: False

work_dir: ${hydra:runtime.cwd}
data_root: ${work_dir}/datasets
log_dir: ./logs
exp_dir: ${hydra:runtime.output_dir}
checkpoint: null
checkpoint_fields: # List of fields to load from checkpoint and override. Loads all if null.
  - model