defaults:
  - _self_
  - datasets:
      - celebahq
  - model: disgan
  - optional local: local.yaml
  - training: full_training_disent
  - evaluation: disent_evaluation

seed: 1
project_name: disentanglement

check_dataset: False

work_dir: ${hydra:runtime.cwd}
data_root: ${work_dir}/datasets
log_dir: ./logs
exp_dir: ${hydra:runtime.output_dir}

generator_pretrained_dir: projects/disentanglement/pretrained_models/stylegan3-r-ffhq-1024x1024.pkl
classifier_pretrained_dir: projects/disentanglement/pretrained_models/classifiers_mlp.pkl

hydra:
  run:
    dir: ${work_dir}