model_name: "arcface"
test_metric: "cosine"
backbone: resnet18
testing_type: face_recognition
use_fprs: [1e-3, 1e-5, 1e-6]
FAR_settings:
  max_samples: 1000
  max_samples_per_ID: 5
local_weights: True
load_backbone: "saved_model"

data_loaders:
  test:
    batch_size: 8
    num_workers: 1
    shuffle: False
metric:
  _target_: src.models.arcface.ArcFace
  in_features: 512
