total_epochs: 200
resume: False
resume_path: None
validate: True
num_gpus: 3

data_loaders:
  train:
    batch_size: 16
    num_workers: 16
    shuffle: True
    split: train
  val:
    batch_size: 16
    num_workers: 16
    shuffle: False
    split: val
