total_epochs: 2
validate: True # True if the model should validate every epoch
num_gpus: 2

data_loaders:
  train:
    batch_size: 8
    num_workers: 4
    shuffle: True
    split: train
  val:
    batch_size: 8
    num_workers: 4
    shuffle: False
    split: val
